Dev-62 stefano projects
alexphiev/collective_website pull request #28
Opened 2024-10-11 20:09 UTC by stefanovnt

- Add Reusa'm project
- Add translations (double check French for edumiam, reusa'm and teamSizeIndividual)

2024-10-13 09:42 UTC, BernardoSCaetano approved these changes

2024-10-13 10:57 UTC, alexphiev requested changes

2024-10-13 10:57 UTC, alexphiev commented on components/layout/sections/project-details.tsx
> +              {teamSize == 1 && t('projects.teamSizeIndividual')}
There is a way to not have to do this check. I can't remember exactly but I think you just need to add the translation ˋteamSize_oneˋ or something like that.

2024-10-14 21:03 UTC, stefanovnt commented on components/layout/sections/project-details.tsx
> +              {teamSize == 1 && t('projects.teamSizeIndividual')}
FIXED! Nice

2024-10-15 17:52 UTC, alexphiev approved these changes

2024-10-15 18:56 UTC, merged